name: Release

on:
  push:
    tags: [ v* ]

jobs:
  release:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      #
      # Setup
      #

      - name: "Select Xcode 12.0.0"
        uses: devbotsxyz/xcode-select@master
        with:
          version: "12.0.0"

      #
      # Build
      #

      - name: "Build"
        uses: devbotsxyz/xcode-build@v1

      #
      # Zip up the app and add it to the GitHub Release as a
      # downloadable asset.
      #

      - name: Package for Distribution
        run: ditto -V -c -k --keepParent "Export/airbrush.bundle" "airbrush.zip"

      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: airbrush.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
